services:
  - type: web
    name: SineWix-Chaturbate
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
